# .travis.yml
language: ruby
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake



notifications:
  slack:
    rooms:
      - sonicstart:W4EazUMcL9NuBkM87g5fjTm2#production
